<?php ob_start(); $title='Register'; ?>
<div class="login_wrapper">
    <div class="animate form login_form">
        <section class="login_content">
            <form method="post" action="">
                <h1>Create Account</h1>
                <div>
                    <input type="text" name="username" class="form-control" placeholder="Username" required="">
                </div>
                <div>
                    <input type="text" name="email" class="form-control" placeholder="Email" required="">
                </div>
                <div>
                    <input type="password" name="password" class="form-control" placeholder="Password" required="">
                </div>
                <div>
                    <input id="password_confirmation" type="password" name="password_confirmation" class="form-control" placeholder="Password Confirmation" required="">
                </div>
                <div>
                    <a class="btn btn-default submit" href="index.html">Submit</a>
                </div>

                <div class="clearfix"></div>

                <div class="separator">
                    <p class="change_link">Already a member ?
                        <a href="<?php echo url('login'); ?>" class="to_register"> Log in </a>
                    </p>

                    <div class="clearfix"></div>
                    <br>

                    <div>
                        <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
                        <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
<?php
$content = ob_get_clean();
ob_end_clean();
require(VIEW_DIR . DS . 'admin' . DS . 'layouts' . DS . 'master.phtml');